# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-02 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(help_text='The first name of the assignee', max_length=100)),
                ('lastname', models.CharField(help_text='The last name of the assignee', max_length=100)),
                ('email', models.EmailField(help_text='Email of the assignee', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The summary of a todo item', max_length=100)),
                ('complete', models.BooleanField(help_text='Whether a todo item is complete or not')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date the todo item was created')),
                ('duedate', models.DateField(help_text='Date the todo item is due')),
                ('notes', models.CharField(help_text='Notes on the summary of the todo item', max_length=250)),
                ('assignees', models.ManyToManyField(to='TodoList.Assignee')),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unqiue identifier for each todo list item', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the tag item', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TodoList.Priority'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='TodoList.Tag'),
        ),
    ]
